# Generated by Django 5.0 on 2023-12-14 13:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                (
                    "date_employment",
                    models.DateField(blank=True, default=datetime.datetime.now),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salary_info", models.CharField(max_length=100)),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Генеральный директор"),
                            (1, "Руководитель высшего звена"),
                            (2, "Менеджер среднего звена"),
                            (3, "Руководитель отдела"),
                            (4, "Обычный сотрудник"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
        ),
    ]
